### ISSUE TITLE
Error @ CLI cmd: scaffold init

### ISSUE THREAD

**Issue by saikarthikp9** [scaffold-sh/cli#1]
I successfully logged into github through UI and then this happens (same results on re-run):
 
› Pick a GitHub repository
  Which repository contains your source code?
⠹     StatusError: Gateway Time-out

**Comment by saikarthikp9** [comment]
I was missing the pre-requisite: yarn
installed using brew: brew install yarn

**Comment by jeremylevy** [comment]
Thank you so much for bringing it to my attention!

I've just pushed a fix to our API :D!

Sorry for the inconvenience,
